service: prometheus-grafana
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  # deploymentBucket:
  #   name: seelaboyinabucket
 
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /{proxy+}
          method: ANY
      - http:
          path: /
          method: ANY
    environment:
      PORT: 3003
